version: '3.7'

volumes:
  dependencies:

services:
  dev:
    build:
      context: .
      dockerfile: ./docker-dev.dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - dependencies:/app/node_modules
    tty: true
